webinfo:
    title: Dockas - seu novo supermercado!
    description: Dockas, seu supermercado 100% online e com frete grátis.
    keywords: Dockas, supermercado BH, supermercado online, frete grátis, free delivery, Belo Horizonte
    favicon: ./assets/images/favicon.png

hostnames:
    webapp: admin.smarttbot.com/
    # api: admin.smarttbot.com/api/v2/
